[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
build = "cp3*"
manylinux-x86_64-image = "sunnycase/manylinux_2_24_x86_64:version1.0"
test-requires = "pytest"
test-command = [
  "pytest {project}/tests/other"
]

[tool.cibuildwheel.linux]
archs = ["x86_64"]
before-build = "pip install https://github.com/sunnycase/auditwheel/releases/download/4.0.0-nncase-2/auditwheel-0.0.0-py3-none-any.whl"
repair-wheel-command = "LD_LIBRARY_PATH=/usr/lib64 auditwheel repair -w {dest_dir} {wheel} --exclude librebound.cpython-36m-x86_64-linux-gnu.so"
