[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
skip = "cp36*"
manylinux-x86_64-image = "manylinux2014"

[tool.cibuildwheel.linux]
archs = ["x86_64"]
before-build = "pip install auditwheel"
repair-wheel-command = "LD_LIBRARY_PATH=/usr/lib64 auditwheel repair -w {dest_dir} {wheel} --exclude librebound.cpython-37m-x86_64-linux-gnu.so,librebound.cpython-38m-x86_64-linux-gnu.so,librebound.cpython-39m-x86_64-linux-gnu.so,librebound.cpython-310m-x86_64-linux-gnu.so" 
