name: REBOUNDx (ipynb)

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest jupyter matplotlib scipy multiprocess
          pip install -r requirements.txt
      - name: Build package
        run: pip install -e .
      - name: Running jupyter notebooks
        run: |
          cd ipython_examples
          python ipynb2py.py CentralForce.ipynb
          python ipynb2py.py CustomSplittingIntegrationSchemes.ipynb
          python ipynb2py.py Custom_Effects.ipynb
          python ipynb2py.py EccAndIncDamping.ipynb

