name: REBOUNDx (python)

on: [push, pull_request, repository_dispatch]

jobs:
  build:
    name: Python tests on ${{ matrix.os }} (${{ matrix.python-version }})
    timeout-minutes: 10

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.11"]
        os: [ubuntu-latest, macos-11]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
      - name: Test
        run: |
          echo "ref: ${{ github.event.client_payload.ref }}"
      - name: checkout REBOUND version that triggered (if triggered)
        uses: actions/checkout@v4
        with: 
          repository: hannorein/rebound
          path: ./rebound
      - name: Build REBOUND
        run: |
          cd rebound
          git checkout -b ${{ github.event.client_payload.ref }}
          pip install -e ./rebound
      - name: Build package
        run: pip install -e .
      - name: Output package contents
        run: |
          pip show reboundx -vf
      - name: Running unittests
        run: |
          python -m unittest discover -s reboundx/test/ -v
